language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
    sources:
      - pov-wkhtmltopdf
#    Search your sources alias here:
#    https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - wkhtmltopdf  # only add if needed and check the before_install section below

before_install:
  - "export DISPLAY=:912.0"
  - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - pip install --user -r requirements.txt
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
   - pip install PyPDF2==1.18

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success